SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

export DATA2VEC_DIALECT_DIR="$SCRIPT_DIR"
export FAIRSEQ_DIR="$REPO_ROOT/fairseq"
export PYTHONPATH="$FAIRSEQ_DIR:$DATA2VEC_DIALECT_DIR:$PYTHONPATH"
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
